// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/recoia/Favorites.tsx": () => import("../components/mockups/recoia/Favorites.tsx"),
  "./components/mockups/recoia/Home.tsx": () => import("../components/mockups/recoia/Home.tsx"),
  "./components/mockups/recoia/Landing.tsx": () => import("../components/mockups/recoia/Landing.tsx"),
  "./components/mockups/recoia/ProductDetail.tsx": () => import("../components/mockups/recoia/ProductDetail.tsx"),
  "./components/mockups/recoia/Profile.tsx": () => import("../components/mockups/recoia/Profile.tsx"),
  "./components/mockups/recoia/Search.tsx": () => import("../components/mockups/recoia/Search.tsx"),
  "./components/mockups/recoia/admin/AIModels.tsx": () => import("../components/mockups/recoia/admin/AIModels.tsx"),
  "./components/mockups/recoia/admin/Analytics.tsx": () => import("../components/mockups/recoia/admin/Analytics.tsx"),
  "./components/mockups/recoia/admin/Categories.tsx": () => import("../components/mockups/recoia/admin/Categories.tsx"),
  "./components/mockups/recoia/admin/Dashboard.tsx": () => import("../components/mockups/recoia/admin/Dashboard.tsx"),
  "./components/mockups/recoia/admin/Logs.tsx": () => import("../components/mockups/recoia/admin/Logs.tsx"),
  "./components/mockups/recoia/admin/Orders.tsx": () => import("../components/mockups/recoia/admin/Orders.tsx"),
  "./components/mockups/recoia/admin/Products.tsx": () => import("../components/mockups/recoia/admin/Products.tsx"),
  "./components/mockups/recoia/admin/Recommendations.tsx": () => import("../components/mockups/recoia/admin/Recommendations.tsx"),
  "./components/mockups/recoia/admin/Reports.tsx": () => import("../components/mockups/recoia/admin/Reports.tsx"),
  "./components/mockups/recoia/admin/Settings.tsx": () => import("../components/mockups/recoia/admin/Settings.tsx"),
  "./components/mockups/recoia/admin/UserDetails.tsx": () => import("../components/mockups/recoia/admin/UserDetails.tsx"),
  "./components/mockups/recoia/admin/Users.tsx": () => import("../components/mockups/recoia/admin/Users.tsx"),
  "./components/mockups/recoia/auth/ForgotPassword.tsx": () => import("../components/mockups/recoia/auth/ForgotPassword.tsx"),
  "./components/mockups/recoia/auth/Login.tsx": () => import("../components/mockups/recoia/auth/Login.tsx"),
  "./components/mockups/recoia/auth/Register.tsx": () => import("../components/mockups/recoia/auth/Register.tsx"),
  "./components/mockups/recoia/auth/ResetPassword.tsx": () => import("../components/mockups/recoia/auth/ResetPassword.tsx"),
  "./components/mockups/recoia/auth/VerifyEmail.tsx": () => import("../components/mockups/recoia/auth/VerifyEmail.tsx"),
  "./components/mockups/recoia/auth/VerifyFailed.tsx": () => import("../components/mockups/recoia/auth/VerifyFailed.tsx"),
  "./components/mockups/recoia/auth/VerifySuccess.tsx": () => import("../components/mockups/recoia/auth/VerifySuccess.tsx")
};
